### ISSUE TITLE
Cleanup Unreceivable Sent High Fives

### ISSUE THREAD

**Issue by a-krawciw** [a-krawciw/high_five_line#1]
If a message is sent before there is a target active it cannot be cleared.

Use a unique ID to remove with a JS timer.

**Comment by guystoppi** [comment]
I didn't end up using a unique ID. When creating a high five, I start a 10 second timer (we might want to extend it). At the end of the timer, I remove the high five.

**Comment by guystoppi** [comment]
Re-resolved with commit 3f4c5a2
